baseURL = 'https://blog.micro-nova.com/'
languageCode = 'en-us'
title = 'MicroNova Engineering Blog'

contentdir = "content"
publishdir = "public"
canonifyurls = true
theme = "hugo-ficurinia"
defaultContentLanguage = "en"
copyright = "MicroNova"

[indexes]
  category = "categories"
  tag = "tags"

[params]
  # These params relate largely to the theme. See the theme readme for details.
  author = "MicroNova"
  logo = "/micronova_logo_white.png"
  logoRightOfTitle = true
  faviconIco = "/favicon.png"
  favicon = "/favicon.png"
  appletouch = "/micronova_square_logo.png"
  icon512 = "/micronova_square_logo.png"
  showRss = false

# The below is used by the theme. Please see the theme readme for details.
[menu]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "https://www.micro-nova.com/about"
        weight = 10
    [[menu.main]]
        identifier = "amplipro"
        name = "AmpliPro"
        url = "https://www.amplipro.com"
        weight = 20
    [[menu.main]]
        identifier = "github"
        name = "GitHub"
        url = "https://github.com/micro-nova"
        weight = 10

# The below is used by the theme. Please see the theme readme for details.
[outputs]
    home = ["HTML", "JSON"]


[deployment]
    [[deployment.targets]]
    # An arbitrary name for this target.
    name = "production"

    # URL specifies the Go Cloud Development Kit URL to deploy to. Examples:
    URL = "gs://blog.micro-nova.com"
