baseURL = 'https://blog.micro-nova.com/'
languageCode = 'en-us'
title = 'Micro-Nova Engineering Blog'

contentdir = "content"
publishdir = "public"
builddrafts = true
canonifyurls = true
author = "admin"
theme = "pixyll"
# disqusShortname = "micronova-blog"


[indexes]
  category = "categories"
  tag = "tags"

[params]
  search_engine = true
  # google_analytics_id = "XX-XXXXXXXX-X"
  # twitter_username = "username"
  paginate = true

[deployment]

[[deployment.targets]]
# An arbitrary name for this target.
name = "production"

# URL specifies the Go Cloud Development Kit URL to deploy to. Examples:
URL = "gs://blog.micro-nova.com"
