name: deploy prod
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: log in to GCP
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          project_id: ${{ secrets.PROJECT_ID }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.DEPLOY_SERVICE_ACCOUNT }}
      - name: 'Set up gcloud'
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: Build & deploy site
        steps:
        - run: apt install hugo
        - run: hugo
        - run: hugo deploy
        - run: gcloud compute url-maps invalidate-cdn-cache blog-prod --path "/*" --async
